[package]
name = "jkq"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
crossbeam-channel = "0.5.15"
rdkafka = { version = "0.39.0", default-features = false, features = ["libz", "ssl-vendored"] }
signal-hook = "0.3.18"
simd-json = "0.15.1"
